; PlatformIO Project Configuration File

[platformio]
src_dir = .

[env]
build_unflags =
    -std=gnu++11
    -std=gnu++14
    -std=gnu++17
    -std=gnu++2a
    -std=gnu++20
build_flags =
    -std=gnu++17
    -fno-exceptions
    -fno-rtti
    -Iinclude

[env:native-example]
platform = native
build_src_filter =
    -<*>
    +<src/client.cpp>
    +<src/codec.cpp>
    +<examples/mcu_async_batch_read.cpp>

[env:rpipico-arduino-example]
platform = raspberrypi
board = pico
framework = arduino
monitor_speed = 115200
build_src_filter =
    -<*>
    +<src/client.cpp>
    +<src/codec.cpp>
    +<examples/platformio_arduino_async/platformio_arduino_async.cpp>

[env:esp32-c3-devkitm-1-example]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
build_src_filter =
    -<*>
    +<src/client.cpp>
    +<src/codec.cpp>
    +<examples/platformio_arduino_async/platformio_arduino_async.cpp>
