#!/usr/bin/env bash
set -euo pipefail

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

export MCPROTOCOL_BAUD="${MCPROTOCOL_BAUD:-38400}"
export MCPROTOCOL_DATA_BITS="${MCPROTOCOL_DATA_BITS:-8}"
export MCPROTOCOL_STOP_BITS="${MCPROTOCOL_STOP_BITS:-2}"
export MCPROTOCOL_PARITY="${MCPROTOCOL_PARITY:-E}"
export MCPROTOCOL_FRAME="${MCPROTOCOL_FRAME:-c4-binary}"
export MCPROTOCOL_SUM_CHECK="${MCPROTOCOL_SUM_CHECK:-on}"
export MCPROTOCOL_STATION="${MCPROTOCOL_STATION:-0}"
export MCPROTOCOL_SERIES="${MCPROTOCOL_SERIES:-ql}"
export MCPROTOCOL_RESPONSE_TIMEOUT_MS="${MCPROTOCOL_RESPONSE_TIMEOUT_MS:-8000}"
export MCPROTOCOL_INTER_BYTE_TIMEOUT_MS="${MCPROTOCOL_INTER_BYTE_TIMEOUT_MS:-1000}"
export MCPROTOCOL_TARGETS="${MCPROTOCOL_TARGETS:-bit:STS10 bit:STC10 word:STN10 bit:TS10 bit:TC10 word:TN10 bit:CS10 bit:CC10 word:CN10 bit:SB10 word:SW10 bit:X10 bit:Y10 bit:M100 bit:L100 bit:F100 bit:B10 word:D100 word:W10 word:Z10 word:R100}"

exec "${script_dir}/supported_device_rw_soak.sh"
