#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

#include "mcprotocol/serial/span_compat.hpp"
#include "mcprotocol/serial/string_view_compat.hpp"

#include "mcprotocol/serial/link_direct.hpp"
#include "mcprotocol/serial/qualified_buffer.hpp"
#include "mcprotocol/serial/types.hpp"

/// \file codec.hpp
/// \brief Frame-level and command-payload-level encode/decode helpers.
///
/// This header is split into two layers:
///
/// - `FrameCodec`: wraps raw command data in the selected serial frame family and decodes full
///   response frames
/// - `CommandCodec`: builds and parses command payloads without the surrounding serial frame bytes

namespace mcprotocol::serial {

/// \brief High-level result of frame decoding.
enum class DecodeStatus : std::uint8_t {
  /// More bytes are required before a full frame can be decoded.
  Incomplete,
  /// One full frame was decoded successfully.
  Complete,
  /// The byte stream is invalid for the selected frame configuration.
  Error
};

/// \brief Raw decoded response frame before command-specific parsing.
struct RawResponseFrame {
  /// Success-with-data, success-without-data, or PLC-error classification.
  ResponseType type = ResponseType::SuccessNoData;
  /// Number of valid bytes in `response_data`.
  std::size_t response_size = 0;
  /// PLC error code when `type == ResponseType::PlcError`.
  std::uint16_t error_code = 0;
  /// Raw response payload bytes with the serial frame already removed.
  std::array<std::uint8_t, kMaxResponseFrameBytes> response_data {};
};

/// \brief Result returned by `FrameCodec::decode_response()`.
struct DecodeResult {
  /// Stream-level decode status.
  DecodeStatus status = DecodeStatus::Incomplete;
  /// Raw response frame when `status == DecodeStatus::Complete`.
  RawResponseFrame frame {};
  /// Decoder-side error when `status == DecodeStatus::Error`.
  Status error {};
  /// Number of bytes consumed from the input span.
  std::size_t bytes_consumed = 0;
};

/// \brief Returns the requested-point value from a sparse native bit result word.
///
/// On `2C`/`3C`/`4C`, native sparse bit reads (`0403`) and monitor reads (`0802`) return the
/// addressed point inside a 16-point mask word. The requested head device is represented by bit `0`
/// of that returned word.
[[nodiscard]] constexpr BitValue sparse_native_requested_bit_value(std::uint32_t raw_value) noexcept {
  return (raw_value & 0x0001U) != 0U ? BitValue::On : BitValue::Off;
}

/// \brief Returns the raw 16-point mask word from a sparse native bit result.
///
/// Keep this raw word visible for diagnostics when the target-specific offset pattern matters.
[[nodiscard]] constexpr std::uint16_t sparse_native_mask_word(std::uint32_t raw_value) noexcept {
  return static_cast<std::uint16_t>(raw_value & 0xFFFFU);
}

/// \brief Frame-level encode/decode helper for complete serial MC frames.
///
/// Use this class when you already have a command payload and only need the outer serial frame
/// layer, or when you need to decode a stream of returned bytes before passing the payload to a
/// command-specific parser.
class FrameCodec {
 public:
  /// \brief Validates a static protocol configuration before encoding requests.
  ///
  /// This checks frame-family / code-mode compatibility, route constraints, and combinations that
  /// are compiled out by feature macros.
  [[nodiscard]] static Status validate_config(const ProtocolConfig& config) noexcept;

  /// \brief Wraps command data in the configured serial frame format.
  ///
  /// `request_data` must already contain the command payload generated by `CommandCodec`.
  [[nodiscard]] static Status encode_request(
      const ProtocolConfig& config,
      std::span<const std::uint8_t> request_data,
      std::span<std::uint8_t> out_frame,
      std::size_t& out_size) noexcept;

  /// \brief Builds a success response frame for tests and local tools.
  ///
  /// This is mainly used by tests and local validation helpers. Library users typically decode real
  /// target responses instead of constructing synthetic ones.
  [[nodiscard]] static Status encode_success_response(
      const ProtocolConfig& config,
      std::span<const std::uint8_t> response_data,
      std::span<std::uint8_t> out_frame,
      std::size_t& out_size) noexcept;

  /// \brief Builds a PLC-error response frame for tests and local tools.
  [[nodiscard]] static Status encode_error_response(
      const ProtocolConfig& config,
      std::uint16_t error_code,
      std::span<std::uint8_t> out_frame,
      std::size_t& out_size) noexcept;

  /// \brief Decodes one response frame from the front of `bytes`.
  ///
  /// The caller can use `bytes_consumed` to drop the decoded prefix and continue stream processing.
  [[nodiscard]] static DecodeResult decode_response(
      const ProtocolConfig& config,
      std::span<const std::uint8_t> bytes) noexcept;
};

/// \brief Command-payload codec helpers below the frame layer.
///
/// These helpers operate on request/response data only. They do not add or remove the surrounding
/// `C1`/`C2`/`C3`/`C4` frame bytes.
namespace CommandCodec {

/// \name Contiguous Device-Memory Read Helpers
/// @{
[[nodiscard]] Status encode_batch_read_words(
    const ProtocolConfig& config,
    const BatchReadWordsRequest& request,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;

[[nodiscard]] Status encode_read_extended_file_register_words(
    const ProtocolConfig& config,
    const ExtendedFileRegisterBatchReadWordsRequest& request,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;

[[nodiscard]] Status encode_direct_read_extended_file_register_words(
    const ProtocolConfig& config,
    const ExtendedFileRegisterDirectBatchReadWordsRequest& request,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;

[[nodiscard]] Status encode_extended_batch_read_words(
    const ProtocolConfig& config,
    const QualifiedBufferWordDevice& device,
    std::uint16_t points,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;

[[nodiscard]] Status encode_link_direct_batch_read_words(
    const ProtocolConfig& config,
    const LinkDirectDevice& device,
    std::uint16_t points,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;

[[nodiscard]] Status parse_batch_read_words_response(
    const ProtocolConfig& config,
    const BatchReadWordsRequest& request,
    std::span<const std::uint8_t> response_data,
    std::span<std::uint16_t> out_words) noexcept;

[[nodiscard]] Status parse_read_extended_file_register_words_response(
    const ProtocolConfig& config,
    std::uint16_t points,
    std::span<const std::uint8_t> response_data,
    std::span<std::uint16_t> out_words) noexcept;

[[nodiscard]] Status parse_extended_batch_read_words_response(
    const ProtocolConfig& config,
    std::uint16_t points,
    std::span<const std::uint8_t> response_data,
    std::span<std::uint16_t> out_words) noexcept;

[[nodiscard]] Status encode_batch_read_bits(
    const ProtocolConfig& config,
    const BatchReadBitsRequest& request,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;

[[nodiscard]] Status encode_link_direct_batch_read_bits(
    const ProtocolConfig& config,
    const LinkDirectDevice& device,
    std::uint16_t points,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;

[[nodiscard]] Status parse_batch_read_bits_response(
    const ProtocolConfig& config,
    const BatchReadBitsRequest& request,
    std::span<const std::uint8_t> response_data,
    std::span<BitValue> out_bits) noexcept;
/// @}

/// \name Contiguous Device-Memory Write Helpers
/// @{
[[nodiscard]] Status encode_batch_write_words(
    const ProtocolConfig& config,
    const BatchWriteWordsRequest& request,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;

[[nodiscard]] Status encode_write_extended_file_register_words(
    const ProtocolConfig& config,
    const ExtendedFileRegisterBatchWriteWordsRequest& request,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;

[[nodiscard]] Status encode_direct_write_extended_file_register_words(
    const ProtocolConfig& config,
    const ExtendedFileRegisterDirectBatchWriteWordsRequest& request,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;

[[nodiscard]] Status encode_link_direct_batch_write_words(
    const ProtocolConfig& config,
    const LinkDirectDevice& device,
    std::span<const std::uint16_t> words,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;

[[nodiscard]] Status encode_extended_batch_write_words(
    const ProtocolConfig& config,
    const QualifiedBufferWordDevice& device,
    std::span<const std::uint16_t> words,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;

[[nodiscard]] Status encode_batch_write_bits(
    const ProtocolConfig& config,
    const BatchWriteBitsRequest& request,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;

[[nodiscard]] Status encode_link_direct_batch_write_bits(
    const ProtocolConfig& config,
    const LinkDirectDevice& device,
    std::span<const BitValue> bits,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;
/// @}

/// \name Random-Access Helpers
/// @{
[[nodiscard]] Status encode_link_direct_random_read(
    const ProtocolConfig& config,
    std::span<const LinkDirectRandomReadItem> items,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;

[[nodiscard]] Status encode_random_read(
    const ProtocolConfig& config,
    const RandomReadRequest& request,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;

[[nodiscard]] Status parse_random_read_response(
    const ProtocolConfig& config,
    std::span<const RandomReadItem> items,
    std::span<const std::uint8_t> response_data,
    std::span<std::uint32_t> out_values) noexcept;

[[nodiscard]] Status encode_random_write_words(
    const ProtocolConfig& config,
    std::span<const RandomWriteWordItem> items,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;

[[nodiscard]] Status encode_random_write_extended_file_register_words(
    const ProtocolConfig& config,
    std::span<const ExtendedFileRegisterRandomWriteWordItem> items,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;

[[nodiscard]] Status encode_link_direct_random_write_words(
    const ProtocolConfig& config,
    std::span<const LinkDirectRandomWriteWordItem> items,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;

[[nodiscard]] Status encode_random_write_bits(
    const ProtocolConfig& config,
    std::span<const RandomWriteBitItem> items,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;

[[nodiscard]] Status encode_link_direct_random_write_bits(
    const ProtocolConfig& config,
    std::span<const LinkDirectRandomWriteBitItem> items,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;
/// @}

/// \name Multi-Block Helpers
/// @{
[[nodiscard]] Status encode_link_direct_multi_block_read(
    const ProtocolConfig& config,
    const LinkDirectMultiBlockReadRequest& request,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;

[[nodiscard]] Status encode_multi_block_read(
    const ProtocolConfig& config,
    const MultiBlockReadRequest& request,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;

[[nodiscard]] Status parse_multi_block_read_response(
    const ProtocolConfig& config,
    std::span<const MultiBlockReadBlock> blocks,
    std::span<const std::uint8_t> response_data,
    std::span<std::uint16_t> out_words,
    std::span<BitValue> out_bits,
    std::span<MultiBlockReadBlockResult> out_results) noexcept;

[[nodiscard]] Status encode_multi_block_write(
    const ProtocolConfig& config,
    const MultiBlockWriteRequest& request,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;

[[nodiscard]] Status encode_link_direct_multi_block_write(
    const ProtocolConfig& config,
    const LinkDirectMultiBlockWriteRequest& request,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;
/// @}

/// \name Monitor Helpers
/// @{
[[nodiscard]] Status encode_register_monitor(
    const ProtocolConfig& config,
    const MonitorRegistration& request,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;

[[nodiscard]] Status encode_register_extended_file_register_monitor(
    const ProtocolConfig& config,
    const ExtendedFileRegisterMonitorRegistration& request,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;

[[nodiscard]] Status encode_link_direct_register_monitor(
    const ProtocolConfig& config,
    const LinkDirectMonitorRegistration& request,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;

[[nodiscard]] Status encode_read_monitor(
    const ProtocolConfig& config,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;

[[nodiscard]] Status encode_read_monitor(
    const ProtocolConfig& config,
    std::span<const RandomReadItem> items,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;

[[nodiscard]] Status encode_read_extended_file_register_monitor(
    const ProtocolConfig& config,
    std::span<const ExtendedFileRegisterAddress> items,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;

[[nodiscard]] Status parse_read_monitor_response(
    const ProtocolConfig& config,
    std::span<const RandomReadItem> items,
    std::span<const std::uint8_t> response_data,
    std::span<std::uint32_t> out_values) noexcept;

[[nodiscard]] Status parse_read_extended_file_register_monitor_response(
    const ProtocolConfig& config,
    std::span<const ExtendedFileRegisterAddress> items,
    std::span<const std::uint8_t> response_data,
    std::span<std::uint16_t> out_words) noexcept;
/// @}

/// \name Serial-Module Dedicated Helpers
/// @{
[[nodiscard]] Status encode_read_user_frame(
    const ProtocolConfig& config,
    const UserFrameReadRequest& request,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;

[[nodiscard]] Status parse_read_user_frame_response(
    const ProtocolConfig& config,
    std::span<const std::uint8_t> response_data,
    UserFrameRegistrationData& out_data) noexcept;

[[nodiscard]] Status encode_write_user_frame(
    const ProtocolConfig& config,
    const UserFrameWriteRequest& request,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;

[[nodiscard]] Status encode_delete_user_frame(
    const ProtocolConfig& config,
    const UserFrameDeleteRequest& request,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;

[[nodiscard]] Status encode_control_global_signal(
    const ProtocolConfig& config,
    const GlobalSignalControlRequest& request,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;

[[nodiscard]] Status encode_initialize_transmission_sequence(
    const ProtocolConfig& config,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;

[[nodiscard]] Status encode_deregister_cpu_monitoring(
    const ProtocolConfig& config,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;
/// @}

/// \name Buffer-Memory Helpers
/// @{
[[nodiscard]] Status encode_read_host_buffer(
    const ProtocolConfig& config,
    const HostBufferReadRequest& request,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;

[[nodiscard]] Status parse_read_host_buffer_response(
    const ProtocolConfig& config,
    const HostBufferReadRequest& request,
    std::span<const std::uint8_t> response_data,
    std::span<std::uint16_t> out_words) noexcept;

[[nodiscard]] Status encode_write_host_buffer(
    const ProtocolConfig& config,
    const HostBufferWriteRequest& request,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;

[[nodiscard]] Status encode_read_module_buffer(
    const ProtocolConfig& config,
    const ModuleBufferReadRequest& request,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;

[[nodiscard]] Status parse_read_module_buffer_response(
    const ProtocolConfig& config,
    const ModuleBufferReadRequest& request,
    std::span<const std::uint8_t> response_data,
    std::span<std::byte> out_bytes) noexcept;

[[nodiscard]] Status encode_write_module_buffer(
    const ProtocolConfig& config,
    const ModuleBufferWriteRequest& request,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;
/// @}

/// \name Diagnostic And Remote-Control Helpers
/// @{
[[nodiscard]] Status encode_read_cpu_model(
    const ProtocolConfig& config,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;

[[nodiscard]] Status parse_read_cpu_model_response(
    const ProtocolConfig& config,
    std::span<const std::uint8_t> response_data,
    CpuModelInfo& out_info) noexcept;

[[nodiscard]] Status encode_remote_run(
    const ProtocolConfig& config,
    RemoteOperationMode mode,
    RemoteRunClearMode clear_mode,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;

[[nodiscard]] Status encode_remote_stop(
    const ProtocolConfig& config,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;

[[nodiscard]] Status encode_remote_pause(
    const ProtocolConfig& config,
    RemoteOperationMode mode,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;

[[nodiscard]] Status encode_remote_latch_clear(
    const ProtocolConfig& config,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;

[[nodiscard]] Status encode_remote_reset(
    const ProtocolConfig& config,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;

[[nodiscard]] Status encode_unlock_remote_password(
    const ProtocolConfig& config,
    std::string_view remote_password,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;

[[nodiscard]] Status encode_lock_remote_password(
    const ProtocolConfig& config,
    std::string_view remote_password,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;

[[nodiscard]] Status encode_clear_error_information(
    const ProtocolConfig& config,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;

[[nodiscard]] Status encode_loopback(
    const ProtocolConfig& config,
    std::span<const char> hex_ascii,
    std::span<std::uint8_t> out_request_data,
    std::size_t& out_size) noexcept;

[[nodiscard]] Status parse_loopback_response(
    const ProtocolConfig& config,
    std::span<const std::uint8_t> response_data,
    std::span<char> out_echoed) noexcept;

/// \brief Converts a logical buffer-memory word address plus module offset into a byte start address.
[[nodiscard]] constexpr std::uint32_t module_buffer_start_address(
    std::uint32_t buffer_memory_address,
    std::uint32_t module_additional_value) noexcept {
  return (buffer_memory_address * 2U) + module_additional_value;
}
/// @}

}  // namespace CommandCodec

}  // namespace mcprotocol::serial
