; このフォルダーをPlatformIOプロジェクトとして開きます。
[platformio]
src_dir = .
default_envs = word

[env]
platform = espressif32@6.12.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
build_unflags =
    -std=gnu++11
    -std=gnu++14
build_flags =
    -std=gnu++17
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DMCPROTOCOL_SERIAL_MAX_REQUEST_FRAME_BYTES=768
    -DMCPROTOCOL_SERIAL_MAX_RESPONSE_FRAME_BYTES=768
    -DMCPROTOCOL_SERIAL_MAX_REQUEST_DATA_BYTES=384
lib_deps =
    mcprotocol-serial-cpp=symlink://../../../plc-comm-mcprotocol-serial-cpp

[env:word]
build_src_filter = -<*> +<word.cpp>

[env:bit]
build_src_filter = -<*> +<bit.cpp>

[env:dword]
build_src_filter = -<*> +<dword.cpp>

[env:float]
build_src_filter = -<*> +<float.cpp>

[env:random]
build_src_filter = -<*> +<random.cpp>

[env:multi_block]
build_src_filter = -<*> +<multi_block.cpp>

[env:async_lcd]
build_src_filter = -<*> +<async_lcd.cpp>
lib_deps =
    ${env.lib_deps}
    m5stack/M5StamPLC@1.2.0
    m5stack/M5Unified@0.2.13
    m5stack/M5GFX@0.2.28
